language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_script:
- dependency-check ./package.json
- dependency-check ./package.json -i jsdoc -i minami -i mocha -i standard -i dependency-check --unused