language: node_js
node_js:
- '0.10'
after_script:
    - NODE_ENV=test
    - istanbul cover ./node_modules/mocha/bin/_mocha test/test.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - rm -rf ./coverage